apiVersion: v1
kind: Secret
metadata:
  name: callhat-db-secret
  namespace: callhat-app
type: Opaque
stringData:
  DATABASE_URL: jdbc:postgresql://10.71.0.3:5432/callhat
  DB_USER: callhat_app
  DB_PASSWORD: 6ubsmV8ofjUITwczVojE
